version: '3.9'

services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: nginx.dockerfile
    image: nginx:inception
    container_name: nginx

  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: mariadb.dockerfile
    image: mariadb:inception
    container_name: mariadb

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: wordpress.dockerfile
    image: wordpress:inception
    container_name: wordpress
