version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    image: nginx:inception
    restart: unless-stopped
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
     - 443:443
    env_file: ./.env
    volumes:
      - www_data:/var/www/html/
    networks:
      - front-tier

  mariadb:
    image: mariadb:inception
    restart: unless-stopped
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile.mariadb
    container_name: mariadb
    env_file: ./.env
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql/
    networks:
      - back-tier

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:inception
    restart: unless-stopped
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile.wordpress
    container_name: wordpress
    expose:
      - 9000
    env_file: ./.env
    volumes:
      - www_data:/var/www/html/
    networks:
      - front-tier
      - back-tier

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hyeonsok/data/db
  www_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hyeonsok/data/www

networks:
  front-tier: {}
  back-tier: {}
