version: '3.9'

services:
  nginx:
    depends_on:
      - wordpress
    image: nginx:inception
    restart: unless-stopped
    build:
      context: ./requirements/nginx/
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
     - 443:443
    env_file: ./.env
    volumes:
      - www_data:/var/www/html/
    networks:
      - default

  mariadb:
    image: mariadb:inception
    restart: unless-stopped
    build:
      context: ./requirements/mariadb/
      dockerfile: mariadb.dockerfile
    container_name: mariadb
    expose:
      - 3306
    environment:
      - MARIADB_DATABASE=${WORDPRESS_DB_NAME}
    volumes:
      - db_data:/var/lib/mysql/
    networks:
      - default

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:inception
    restart: unless-stopped
    build:
      context: ./requirements/wordpress/
      dockerfile: wordpress.dockerfile
    container_name: wordpress
    expose:
      - 9000
    env_file: ./.env
    volumes:
      - www_data:/var/www/html/
    networks:
      - default

volumes:
  db_data: {}
  www_data: {}

networks:
  default: {}
